[package]
name = "logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
all_asserts = "2.3.1"
chrono = "0.4.34"
lazy_static = "1.4.0"
